### ISSUE TITLE
Issue in kpt rpkg command

### ISSUE THREAD

**Issue by SamarSidharth** [kptdev/kpt#4072]
### Expected behavior
`kpt alpha rpkg get` should list the packages
### Actual behavior
The command returns error

```shell
# kpt alpha rpkg get
Error: an error on the server ("unknown") has prevented the request from succeeding (get packagerevisions.porch.kpt.dev)
```

### Information

I investigated it further and found that it was due to authentications issues with few repositories due to which they were in not ready state.
It got resolved once I unregistered these repositories

### Steps to reproduce the behavior

**Comment by johnbelamaric** [comment]
Which version of Porch are you running?

**Comment by johnbelamaric** [comment]
I ask because recent versions include this fix: https://github.com/kptdev/kpt/pull/4038

**Comment by SamarSidharth** [comment]
Thanks @johnbelamaric for a prompt response. The kpt version we use are 1.0.0-beta.38 and 1.0.0-beta.44 and porch server image is porch-server:v0.0.20 and porch-server:v0.0.27
Is there anyother way to get the porch version
