### ISSUE TITLE
[Question] Adding simple build steps to Kptfile

### ISSUE THREAD

**Issue by lbenezriravin** [kptdev/kpt#4081]
I have a package that needs to deploy some non-trivial config files in a configMap. I don't want to maintain the contents of these files as an inline string-in-yaml. The solution I've seen is to maintain the actual files I want and run `kubectl create configmap --from-file <file> -o yaml > configmap.yaml` before deployment. This would be trivial to do in a bash script or Makefile, but adding another layer of abstraction onto the build feels bad.

Is there an idiomatic solution to generating the actual `configmap.yaml` value within a `kpt fn render` command? The solutions I've found are:

1. Write a whole function for this and reference that. While this appears to be the cleanest solution, it also feels nuclear when I just need to run a single command.

2. Throw this into an `exec` mutator. I don't think that forcing the above command into a format that works within the structure of a kpt mutator would actually be cleaner or easier than maintaining a separate bash script. Once I've called `xargs` from within third-party software I usually re-evaluate what I'm doing.

3. Just put it in a Makefile. This is by far the easiest solution I can see but it Feels Bad so I thought I'd ask here to see if there's something cleaner.

4. Is there a better way of maintaining config files outside of a literal in configMap that plays better with kpt? It could be I'm entirely barking up the wrong tree.

Thanks in advance for the help!

**Comment by johnbelamaric** [comment]
https://github.com/nephio-project/nephio/tree/main/krm-functions/gen-configmap-fn

May be useful

**Comment by johnbelamaric** [comment]
It's not really what you're looking for though. But you could adapt it to just wrap a file. Or perhaps write a new function (it just needs to be written once...).

**Comment by lbenezriravin** [comment]
Thank @johnbelamaric , good to know of those functions. I'm really trying to avoid putting another reimplimentation out into the ecosystem, but it looks like https://github.com/kptdev/kpt/issues/3119 hits what I'm looking for. I'll wait another day or so, but I'm ready to close this with "on the roadmap" as a resolution.
