### ISSUE TITLE
gcr.io/kpt-dev/kpt and kpt-gcloud not available

### ISSUE THREAD

**Issue by frits-v** [kptdev/kpt#4155]
### Expected behavior
Can pull or list images from public repo as documented

### Actual behavior

Cannot pull or list images.

```
❯ crane ls gcr.io/kpt-dev/kpt
Error: reading tags for gcr.io/kpt-dev/kpt: GET https://gcr.io/v2/kpt-dev/kpt/tags/list?n=1000: DENIED: Failed to read tags for host 'gcr.io', repository '/v2/kpt-dev/kpt/tags/list?n=1000'
```

Further effects are that the kpt-fn pipelines don't work as intended because they rely on the kpt container image as well.

### Information

The repo is either removed or no longer publicly accessible. Please update the documentation with its new location.

### Steps to reproduce the behavior

**Comment by AndrewW85** [comment]
We are experiencing the same behavior at my company.
```
~ % docker pull gcr.io/kpt-dev/kpt-gcloud             
Using default tag: latest
Error response from daemon: pull access denied for gcr.io/kpt-dev/kpt-gcloud, repository does not exist or may require 'docker login': denied: Permission denied for "latest" from request "/v2/kpt-dev/kpt-gcloud/manifests/latest".

~ % docker image pull gcr.io/kpt-dev/kpt              
Using default tag: latest
Error response from daemon: pull access denied for gcr.io/kpt-dev/kpt, repository does not exist or may require 'docker login': denied: Permission denied for "latest" from request "/v2/kpt-dev/kpt/manifests/latest".
```

**Comment by dpangier** [comment]
This is actually worse than it seems - build pipelines using `kpt apply-setters` fail because the tool uses images to run commands and none of those images are accessible any more. :-(

**Comment by vs-odie** [comment]
has anyone already a solution for that issue? all our pipielines are broken now, because kpt functions cannot get pulled because of permission errors any more

**Comment by dpangier** [comment]
Looks like it's been fixed. Thanks

**Comment by mbacarella** [comment]
Still broken for us.

**Comment by mortent** [comment]
We are aware of the issue and we are working on finding a solution. Apologies for the inconvenience.

**Comment by mortent** [comment]
We have made the latest kpt and kpt-gcloud images available under `gcr.io/kpt-fn/kpt` and `gcr.io/kpt-fn/kpt-gcloud`.

**Comment by yuwenma** [comment]
To add a supplementary to what @mortent suggested. The kpt functions should work if you use the default “unstable” tag. For example, apply-setter should be pulling from gcr.io/kpt-fn/apply-setter:unstable.

**Comment by mortent** [comment]
Closing this issue now, but feel free to re-open if anyone still has problems with the kpt images.
